

# Menu that will appear in the fixed position navbar.
navmenu:
  - name: Archives
    url: /archives
    fa-icon: ~
  - name: Tags
    url: /tags
    fa-icon: ~
  - name: Categories
    url: /categories
    fa-icon: ~


# The CSS files to load in the header.
css:
  - css/normalize.css
  - css/style.css

rcss:
  - url: https://use.fontawesome.com/releases/v5.6.3/css/all.css
    integrity: "sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"

