

# Menu that will appear in the fixed position navbar.
navmenu:
  - name: Archives
    url: /archives
    fa_icon: archive
  - name: Tags
    url: /tags
    fa_icon: tags
  - name: Categories
    url: /categories
    fa_icon: folder


# The CSS files to load in the header.
css:
  - css/normalize.css
  - css/style.css

rcss:
  - url: https://use.fontawesome.com/releases/v5.6.3/css/all.css
    integrity: "sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"



technogrid:
  maxParticles: 20
  particleSize:
    min: 40
    max: 80
  particleDistance:
    min: 10
    max: 20
  particleSpeed:
    min: 50
    max: 100
  particleLife:
    min: 15
    max: 30
  particlesAttract: false
  particlesAxisAligned: true
  boxSize: 30
  boxSpacing: 1
  boxColor:
    r: 14
    g: 25
    b: 14
  edgeColor:
    r: 31
    g: 28
    b: 32
  glowColor:
    r: 224
    g: 164
    b: 88



