

# Menu that will appear in the fixed position navbar.
navmenu:
  - name: Archives
    url: /archives
    fa-icon: ~
  - name: Tags
    url: /tags
    fa-icon: ~
  - name: Categories
    url: /categories
    fa-icon: ~


# The CSS files to load in the header.
css:
  - css/normalize.css
  - css/style.css


